export const LOGIN  = 'LOGIN'
export const AUTH_SIGN_IN  = 'AUTH_SIGN_IN'
export const AUTH_LOGOUT  = 'AUTH_LOGOUT'
export const AUTH_SUCCESS  = 'AUTH_SUCCESS'
export const AUTHENTICATE  = 'AUTHENTICATE'